# Generated by Django 3.1.5 on 2021-02-24 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admins',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('email', models.CharField(max_length=30, verbose_name='email')),
                ('password', models.CharField(max_length=20, verbose_name='password')),
                ('first_name', models.CharField(max_length=20, verbose_name='name')),
                ('last_name', models.CharField(max_length=30, verbose_name='last name')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Componet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('component_name', models.CharField(max_length=60, verbose_name='component Name')),
            ],
            options={
                'verbose_name': 'Component',
                'verbose_name_plural': 'Component',
            },
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=20, verbose_name='name')),
                ('start', models.CharField(max_length=11, verbose_name='start')),
                ('end', models.CharField(max_length=11, verbose_name='end')),
                ('monday_start', models.CharField(blank=True, default='', max_length=6, null=True, verbose_name='monday_start')),
                ('monday_end', models.CharField(blank=True, default='', max_length=6, null=True, verbose_name='monday_end')),
                ('tuesday_start', models.CharField(blank=True, default='', max_length=6, null=True, verbose_name='tuesday_start')),
                ('tuesday_end', models.CharField(blank=True, default='', max_length=6, null=True, verbose_name='tuesday_end')),
                ('wednesday_start', models.CharField(blank=True, default='', max_length=6, null=True, verbose_name='wednesday_start')),
                ('wednesday_end', models.CharField(blank=True, default='', max_length=6, null=True, verbose_name='wednesday_end')),
                ('thursday_start', models.CharField(blank=True, default='', max_length=6, null=True, verbose_name='thursday_start')),
                ('thursday_end', models.CharField(blank=True, default='', max_length=6, null=True, verbose_name='thursday_end')),
                ('friday_start', models.CharField(blank=True, default='', max_length=6, null=True, verbose_name='friday_start')),
                ('friday_end', models.CharField(blank=True, default='', max_length=6, null=True, verbose_name='friday_end')),
                ('saturday_start', models.CharField(blank=True, default='', max_length=6, null=True, verbose_name='saturday_start')),
                ('saturday_end', models.CharField(blank=True, default='', max_length=6, null=True, verbose_name='saturday_end')),
                ('sunday_start', models.CharField(blank=True, default='', max_length=6, null=True, verbose_name='sunday')),
                ('sunday_end', models.CharField(blank=True, default='', max_length=6, null=True, verbose_name='sunday')),
            ],
            options={
                'verbose_name': 'Group',
                'verbose_name_plural': 'Groups',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('name1', models.CharField(max_length=30, verbose_name='name1')),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Languages',
            },
        ),
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=20, verbose_name='name')),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Languages',
            },
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=20, verbose_name='name')),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
            },
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('first_name', models.CharField(max_length=20, verbose_name='name')),
                ('last_name', models.CharField(max_length=30, verbose_name='last name')),
                ('email', models.CharField(default='example@gmail.com', max_length=30, verbose_name='email')),
                ('phone_number', models.CharField(default='+374 93606060', max_length=30, verbose_name='phone_number')),
                ('linkedin_link', models.CharField(max_length=100, verbose_name='link')),
                ('monday_start', models.CharField(blank=True, default='', max_length=6, null=True, verbose_name='monday_start')),
                ('monday_end', models.CharField(blank=True, default='', max_length=6, null=True, verbose_name='monday_end')),
                ('tuesday_start', models.CharField(blank=True, default='', max_length=6, null=True, verbose_name='tuesday_start')),
                ('tuesday_end', models.CharField(blank=True, default='', max_length=6, null=True, verbose_name='tuesday_end')),
                ('wednesday_start', models.CharField(blank=True, default='', max_length=6, null=True, verbose_name='wednesday_start')),
                ('wednesday_end', models.CharField(blank=True, default='', max_length=6, null=True, verbose_name='wednesday_end')),
                ('thursday_start', models.CharField(blank=True, default='', max_length=6, null=True, verbose_name='thursday_start')),
                ('thursday_end', models.CharField(blank=True, default='', max_length=6, null=True, verbose_name='thursday_end')),
                ('friday_start', models.CharField(blank=True, default='', max_length=6, null=True, verbose_name='friday_start')),
                ('friday_end', models.CharField(blank=True, default='', max_length=6, null=True, verbose_name='friday_end')),
                ('saturday_start', models.CharField(blank=True, default='', max_length=6, null=True, verbose_name='saturday_start')),
                ('saturday_end', models.CharField(blank=True, default='', max_length=6, null=True, verbose_name='saturday_end')),
                ('sunday_start', models.CharField(blank=True, default='', max_length=6, null=True, verbose_name='sunday')),
                ('sunday_end', models.CharField(blank=True, default='', max_length=6, null=True, verbose_name='sunday')),
                ('isArchived', models.BooleanField(default=False, verbose_name='isArchived')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherLanguages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminUI.language')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminUI.teachers')),
            ],
        ),
        migrations.CreateModel(
            name='SubSubjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='name')),
                ('parentSubject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminUI.subjects')),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('first_name', models.CharField(max_length=20, verbose_name='first_name')),
                ('last_name', models.CharField(max_length=30, verbose_name='last_name')),
                ('email', models.CharField(max_length=50, verbose_name='email')),
                ('phone_number', models.CharField(max_length=9, verbose_name='phone_number')),
                ('phone_number_code', models.CharField(max_length=4, verbose_name='phone_number_code')),
                ('contract_number', models.CharField(max_length=9, verbose_name='contract_number')),
                ('contract_number_code', models.CharField(max_length=4, verbose_name='contract_number_code')),
                ('passport_type', models.CharField(max_length=13, verbose_name='passport_type')),
                ('passport_number', models.CharField(max_length=13, verbose_name='passport_number')),
                ('address', models.CharField(max_length=25, verbose_name='addres')),
                ('date_of_birth', models.CharField(max_length=11, verbose_name='date_of_birth')),
                ('contract_start', models.CharField(max_length=11, verbose_name='contract_start')),
                ('contract_end', models.CharField(max_length=11, verbose_name='contract_end')),
                ('priceM', models.IntegerField(verbose_name='priceM')),
                ('price', models.IntegerField(verbose_name='price')),
                ('passportPic', models.CharField(max_length=20000, verbose_name='image')),
                ('isArchived', models.BooleanField(default=False, verbose_name='isArchived')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminUI.groups')),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminUI.language')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('Description', models.CharField(max_length=300, verbose_name='description')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminUI.languages')),
            ],
        ),
        migrations.CreateModel(
            name='Lesonss',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('Description', models.CharField(max_length=300, verbose_name='description')),
                ('file', models.FileField(null=True, upload_to='')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminUI.componet')),
            ],
        ),
        migrations.AddField(
            model_name='languages',
            name='parentSubject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminUI.subsubjects'),
        ),
        migrations.AddField(
            model_name='language',
            name='parentSubject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminUI.subjects'),
        ),
        migrations.AddField(
            model_name='groups',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminUI.language'),
        ),
        migrations.AddField(
            model_name='groups',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminUI.teachers'),
        ),
        migrations.CreateModel(
            name='Group_lesons',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('id_lesons', models.CharField(default='', max_length=50, verbose_name='id_lesons')),
                ('lesons_name', models.CharField(max_length=50, verbose_name='lesons_name')),
                ('data_leson', models.CharField(max_length=50, verbose_name='data_lesons')),
                ('data_leson_number', models.CharField(default='', max_length=50, verbose_name='data_leson_number')),
                ('leson_time_start', models.CharField(max_length=50, verbose_name='leson_time_start')),
                ('leson_time_end', models.CharField(max_length=50, verbose_name='leson_time_end')),
                ('leson_component_name', models.CharField(default='', max_length=50, verbose_name='component_leson')),
                ('status', models.CharField(default='', max_length=15, verbose_name='status')),
                ('parent_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminUI.groups')),
            ],
        ),
        migrations.AddField(
            model_name='componet',
            name='languages',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminUI.language'),
        ),
    ]
