# Generated by Django 2.2.12 on 2021-07-29 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminUI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admins',
            name='company_name',
            field=models.CharField(max_length=60, null=True, verbose_name='company_name'),
        ),
        migrations.AddField(
            model_name='admins',
            name='phone_number',
            field=models.CharField(max_length=15, null=True, verbose_name='phone_number'),
        ),
    ]
