# Generated by Django 3.1.5 on 2021-02-24 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminUI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='changes',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='changes'),
        ),
        migrations.AddField(
            model_name='groups',
            name='dayTimes',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='dayTimes'),
        ),
    ]
