# Generated by Django 2.2.12 on 2021-07-29 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminUI', '0002_auto_20210729_0803'),
    ]

    operations = [
        migrations.AddField(
            model_name='admins',
            name='logo',
            field=models.FileField(null=True, upload_to='', verbose_name='logo'),
        ),
    ]
