# Generated by Django 3.1.5 on 2021-03-02 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminUI', '0002_auto_20210224_1649'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students_info_group_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_attend_grops_data', models.CharField(max_length=50, verbose_name='start_attend_grops_data')),
                ('end_attend_grops_data', models.CharField(max_length=50, verbose_name='end_attend_grops_data')),
                ('grups', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminUI.groups')),
                ('students', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminUI.students')),
            ],
        ),
        migrations.CreateModel(
            name='StudentLanguages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminUI.language')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminUI.students')),
            ],
        ),
    ]
