# Generated by Django 3.1.5 on 2021-03-02 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminUI', '0003_studentlanguages_students_info_group_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students_info_group_data',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
