# Generated by Django 3.1.5 on 2021-03-02 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminUI', '0004_auto_20210302_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='students_info_group_data',
            name='status',
            field=models.BooleanField(default=False, verbose_name='status'),
        ),
    ]
