# Generated by Django 3.1.5 on 2021-03-02 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminUI', '0005_students_info_group_data_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='students_info_group_data',
            name='end_attend_grops_time',
            field=models.CharField(default='-', max_length=50, verbose_name='end_attend_grops_time'),
        ),
        migrations.AddField(
            model_name='students_info_group_data',
            name='start_attend_grops_time',
            field=models.CharField(default='-', max_length=50, verbose_name='start_attend_grops_time'),
        ),
    ]
