# Generated by Django 3.1.5 on 2021-03-02 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminUI', '0006_auto_20210302_1131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentlanguages',
            old_name='teacher',
            new_name='student',
        ),
    ]
