# Generated by Django 3.1.5 on 2021-03-04 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminUI', '0008_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room_grup_week',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminUI.groups')),
            ],
            options={
                'verbose_name': 'Room_Grops_Week',
                'verbose_name_plural': 'Room_Grops_Week',
            },
        ),
    ]
