# Generated by Django 3.1.5 on 2021-03-04 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminUI', '0009_room_grup_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='room_grup_week',
            name='monday',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminUI.room'),
        ),
        migrations.AlterField(
            model_name='room_grup_week',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
