# Generated by Django 3.1.5 on 2021-03-04 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminUI', '0010_auto_20210304_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='room_grup_week',
            name='friday',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='friday', to='adminUI.room'),
        ),
        migrations.AddField(
            model_name='room_grup_week',
            name='saturday',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saturday', to='adminUI.room'),
        ),
        migrations.AddField(
            model_name='room_grup_week',
            name='sunday',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sunday', to='adminUI.room'),
        ),
        migrations.AddField(
            model_name='room_grup_week',
            name='thursday',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thursday', to='adminUI.room'),
        ),
        migrations.AddField(
            model_name='room_grup_week',
            name='tuesday',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tuesday', to='adminUI.room'),
        ),
        migrations.AddField(
            model_name='room_grup_week',
            name='wednesday',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wednesday', to='adminUI.room'),
        ),
        migrations.AlterField(
            model_name='room_grup_week',
            name='monday',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monday', to='adminUI.room'),
        ),
    ]
