# Generated by Django 3.1.5 on 2021-03-10 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminUI', '0011_auto_20210304_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group_lesons',
            name='data_leson',
            field=models.CharField(default='', max_length=50, verbose_name='data_lesons'),
        ),
        migrations.AlterField(
            model_name='group_lesons',
            name='leson_time_end',
            field=models.CharField(default='', max_length=50, verbose_name='leson_time_end'),
        ),
        migrations.AlterField(
            model_name='group_lesons',
            name='leson_time_start',
            field=models.CharField(default='', max_length=50, verbose_name='leson_time_start'),
        ),
        migrations.AlterField(
            model_name='group_lesons',
            name='lesons_name',
            field=models.CharField(default='', max_length=50, verbose_name='lesons_name'),
        ),
    ]
