# Generated by Django 3.1.5 on 2021-03-10 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminUI', '0012_auto_20210310_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group_lesons',
            name='data_leson',
            field=models.CharField(max_length=50, null=True, verbose_name='data_lesons'),
        ),
        migrations.AlterField(
            model_name='group_lesons',
            name='data_leson_number',
            field=models.CharField(max_length=50, null=True, verbose_name='data_leson_number'),
        ),
        migrations.AlterField(
            model_name='group_lesons',
            name='id_lesons',
            field=models.CharField(max_length=50, null=True, verbose_name='id_lesons'),
        ),
        migrations.AlterField(
            model_name='group_lesons',
            name='leson_component_name',
            field=models.CharField(max_length=50, null=True, verbose_name='component_leson'),
        ),
        migrations.AlterField(
            model_name='group_lesons',
            name='leson_time_end',
            field=models.CharField(max_length=50, null=True, verbose_name='leson_time_end'),
        ),
        migrations.AlterField(
            model_name='group_lesons',
            name='leson_time_start',
            field=models.CharField(max_length=50, null=True, verbose_name='leson_time_start'),
        ),
        migrations.AlterField(
            model_name='group_lesons',
            name='lesons_name',
            field=models.CharField(max_length=50, null=True, verbose_name='lesons_name'),
        ),
    ]
