# Generated by Django 3.1.5 on 2021-03-10 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminUI', '0013_auto_20210310_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group_lesons',
            name='status',
            field=models.CharField(max_length=15, null=True, verbose_name='status'),
        ),
    ]
