# Generated by Django 3.1.5 on 2021-03-18 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminUI', '0014_auto_20210310_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentlanguages',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminUI.componet'),
        ),
    ]
