# Generated by Django 3.1.5 on 2021-03-19 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminUI', '0015_auto_20210318_0719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='passportPic',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
