# Generated by Django 3.1.5 on 2021-03-19 12:34

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminUI', '0016_auto_20210319_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='passportPic',
            field=models.ImageField(null=True, storage=django.core.files.storage.FileSystemStorage(location='/media/photos_pasport'), upload_to=''),
        ),
    ]
