# Generated by Django 3.1.5 on 2021-03-19 12:51

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminUI', '0017_auto_20210319_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='pictures_studnet',
            field=models.ImageField(null=True, storage=django.core.files.storage.FileSystemStorage(location='/media/photos_pasport'), upload_to=''),
        ),
    ]
