# Generated by Django 3.1.5 on 2021-03-19 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminUI', '0018_students_pictures_studnet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='passportPic',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='students',
            name='pictures_studnet',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
