# Generated by Django 3.1.5 on 2021-04-07 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminUI', '0019_auto_20210319_1308'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment_student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('paid_amount', models.IntegerField(null=True, verbose_name='paint_amout')),
                ('comment', models.CharField(max_length=200, null=True, verbose_name='comment')),
                ('file_payment', models.FileField(upload_to='', verbose_name='File')),
                ('data', models.DateField(null=True, verbose_name='data')),
                ('parent_studnet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminUI.students')),
            ],
            options={
                'verbose_name': 'Payment Student',
                'verbose_name_plural': 'Payment Students',
            },
        ),
    ]
