# Generated by Django 2.2.12 on 2021-04-09 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminUI', '0020_payment_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='price_sale',
            field=models.IntegerField(default=0, verbose_name='price_sale'),
        ),
    ]
