# Generated by Django 2.2.12 on 2021-04-09 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminUI', '0021_students_price_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='priceM_sale',
            field=models.IntegerField(null=True, verbose_name='price_sale'),
        ),
    ]
