# Generated by Django 2.2.12 on 2021-04-09 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminUI', '0022_students_pricem_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='priceM_sale',
            field=models.IntegerField(null=True, verbose_name='priceM_sale'),
        ),
    ]
