# Generated by Django 2.2.12 on 2021-04-09 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminUI', '0023_auto_20210409_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherlanguages',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminUI.Componet'),
        ),
    ]
