# Generated by Django 2.2.12 on 2021-04-15 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminUI', '0024_auto_20210409_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='password',
            field=models.CharField(blank=True, max_length=25, verbose_name='password'),
        ),
    ]
