# Generated by Django 2.2.12 on 2021-04-19 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminUI', '0025_students_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='activ',
            field=models.BooleanField(default=False, verbose_name='Activat'),
        ),
    ]
