# Generated by Django 2.2.12 on 2021-04-20 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminUI', '0028_teachers_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='admins',
            name='role',
            field=models.CharField(default='Super Admin', max_length=20, verbose_name='role_user'),
        ),
        migrations.AddField(
            model_name='teachers',
            name='role',
            field=models.CharField(default='Teacher', max_length=20, verbose_name='role_user'),
        ),
    ]
