# Generated by Django 2.2.12 on 2021-04-21 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminUI', '0029_auto_20210420_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesonss',
            name='isArchived',
            field=models.BooleanField(default=False, verbose_name='isArchived'),
        ),
    ]
