# Generated by Django 2.2.12 on 2021-04-21 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminUI', '0030_lesonss_isarchived'),
    ]

    operations = [
        migrations.AddField(
            model_name='componet',
            name='isArchived',
            field=models.BooleanField(default=False, verbose_name='isArchived'),
        ),
    ]
