# Generated by Django 2.2.12 on 2021-04-27 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminUI', '0033_teachers_pictures_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='admins',
            name='pictures_Admin',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
