# Generated by Django 2.2.12 on 2021-04-28 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminUI', '0034_admins_pictures_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='group_lesons',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminUI.Room'),
        ),
        migrations.AddField(
            model_name='group_lesons',
            name='shedul_leson',
            field=models.BooleanField(default=False),
        ),
    ]
