# Generated by Django 2.2.12 on 2021-04-28 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminUI', '0036_auto_20210428_0758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group_lesons',
            name='shedul_leson',
            field=models.BooleanField(default=False, null=True, verbose_name='shedul_leson'),
        ),
    ]
