# Generated by Django 2.2.12 on 2021-04-30 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminUI', '0037_auto_20210428_0758'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_student',
            name='send_mail',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
