# Generated by Django 2.2.12 on 2021-05-04 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminUI', '0039_group_lesons_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='comment',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='comment'),
        ),
    ]
