# Generated by Django 2.2.12 on 2021-05-04 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminUI', '0040_students_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='comment',
            field=models.CharField(blank=True, default=' ', max_length=250, null=True, verbose_name='comment'),
        ),
    ]
