# Generated by Django 2.2.12 on 2021-05-05 08:01

import adminUI.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminUI', '0041_auto_20210504_0821'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('from_message', models.CharField(max_length=50, null=True, verbose_name='from')),
                ('to_message', models.CharField(max_length=50, null=True, verbose_name='from')),
                ('message', models.CharField(max_length=1000, null=True, verbose_name='from')),
                ('data', models.DateTimeField(null=True, verbose_name='data_time')),
                ('x', models.ForeignKey(blank=True, null=True, on_delete=adminUI.models.Teachers, to='adminUI.Students')),
            ],
        ),
    ]
