# Generated by Django 2.2.12 on 2021-05-05 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminUI', '0042_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='x',
        ),
    ]
