# Generated by Django 2.2.12 on 2021-05-05 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminUI', '0043_remove_message_x'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.CharField(max_length=1000, null=True, verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='message',
            name='to_message',
            field=models.CharField(max_length=50, null=True, verbose_name='To'),
        ),
    ]
