# Generated by Django 2.2.12 on 2021-05-05 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminUI', '0044_auto_20210505_0811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='from_message',
        ),
        migrations.RemoveField(
            model_name='message',
            name='to_message',
        ),
    ]
