# Generated by Django 2.2.12 on 2021-05-05 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminUI', '0045_auto_20210505_0831'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='from_message_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_message_admin', to='adminUI.Admins'),
        ),
        migrations.AddField(
            model_name='message',
            name='from_message_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_message_teacher', to='adminUI.Teachers'),
        ),
        migrations.AddField(
            model_name='message',
            name='to_message_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_message_admin', to='adminUI.Admins'),
        ),
        migrations.AddField(
            model_name='message',
            name='to_message_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_message_teacher', to='adminUI.Teachers'),
        ),
    ]
