# Generated by Django 2.2.12 on 2021-05-07 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminUI', '0046_auto_20210505_0834'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='status',
            field=models.BooleanField(default=False, null=True, verbose_name='reded'),
        ),
    ]
