# Generated by Django 2.2.12 on 2021-05-07 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminUI', '0047_message_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admins',
            old_name='pictures_Admin',
            new_name='pictures_teacher',
        ),
    ]
