# Generated by Django 2.2.12 on 2021-05-10 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminUI', '0048_auto_20210507_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers',
            name='pictures_teacher',
            field=models.ImageField(default='default_img.jpg', null=True, upload_to=''),
        ),
    ]
