# Generated by Django 2.2.12 on 2021-05-10 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminUI', '0049_auto_20210510_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers',
            name='pictures_teacher',
            field=models.ImageField(default='photo_teacher/default_img.jpg', null=True, upload_to=''),
        ),
    ]
