# Generated by Django 2.2.12 on 2021-05-13 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminUI', '0051_auto_20210510_1247'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message_files',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('message_image', models.ImageField(null=True, upload_to='img/message_img/')),
                ('parent_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminUI.Message')),
            ],
        ),
    ]
