# Generated by Django 2.2.12 on 2021-05-14 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminUI', '0053_auto_20210514_1018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='delete_to',
        ),
    ]
