# Generated by Django 3.1.8 on 2021-05-24 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminUI', '0054_remove_message_delete_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='users_table',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('data_end_message', models.DateTimeField(null=True, verbose_name='data_time')),
                ('end_message', models.CharField(max_length=1000, null=True, verbose_name='end_message')),
                ('from_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_admin', to='adminUI.admins')),
                ('from_teahcer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_teacher', to='adminUI.teachers')),
                ('to_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_admin', to='adminUI.admins')),
                ('to_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_teacher', to='adminUI.teachers')),
            ],
        ),
    ]
