# Generated by Django 3.1.8 on 2021-06-07 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminUI', '0055_users_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachers',
            name='parent_admin',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='adminUI.admins'),
        ),
    ]
