# Generated by Django 3.1.8 on 2021-06-08 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminUI', '0056_teachers_parent_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='componet',
            name='parent_admin',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='adminUI.admins'),
        ),
        migrations.AddField(
            model_name='groups',
            name='parent_admin',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='adminUI.admins'),
        ),
        migrations.AddField(
            model_name='language',
            name='parent_admin',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='adminUI.admins'),
        ),
        migrations.AddField(
            model_name='languages',
            name='parent_admin',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='adminUI.admins'),
        ),
        migrations.AddField(
            model_name='lesonss',
            name='parent_admin',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='adminUI.admins'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='parent_admin',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='adminUI.admins'),
        ),
        migrations.AddField(
            model_name='room',
            name='parent_admin',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='adminUI.admins'),
        ),
        migrations.AddField(
            model_name='students',
            name='parent_admin',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='adminUI.admins'),
        ),
        migrations.AddField(
            model_name='subjects',
            name='parent_admin',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='adminUI.admins'),
        ),
        migrations.AddField(
            model_name='subsubjects',
            name='parent_admin',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='adminUI.admins'),
        ),
    ]
