# Generated by Django 3.1.8 on 2021-06-08 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminUI', '0057_auto_20210608_0756'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_student',
            name='parent_admin',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='adminUI.admins'),
        ),
    ]
