# Generated by Django 3.1.8 on 2021-06-08 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminUI', '0058_payment_student_parent_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='users_table',
            name='parent_admin',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='adminUI.admins'),
        ),
    ]
