# Generated by Django 3.1.8 on 2021-06-11 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminUI', '0059_users_table_parent_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group_lesons',
            name='shedul_leson',
            field=models.BooleanField(default=False, verbose_name='shedul_leson'),
        ),
    ]
