# Generated by Django 3.1.8 on 2021-06-14 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminUI', '0060_auto_20210611_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group_lesons',
            name='shedul_leson',
            field=models.BooleanField(default=False, null=True, verbose_name='shedul_leson'),
        ),
    ]
