# Generated by Django 3.1.8 on 2021-06-15 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminUI', '0061_auto_20210614_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachers',
            name='language_login_site',
            field=models.CharField(blank=True, default='arm', max_length=7, null=True, verbose_name='language_login_site'),
        ),
    ]
