# Generated by Django 3.1.8 on 2021-06-15 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminUI', '0062_teachers_language_login_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='admins',
            name='language_login_site',
            field=models.CharField(blank=True, default='arm', max_length=7, null=True, verbose_name='language_login_site'),
        ),
    ]
