# Generated by Django 3.1.8 on 2021-06-21 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminUI', '0063_admins_language_login_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='admins',
            name='sigun_in_one',
            field=models.BooleanField(default=False, verbose_name='sigun_in_one'),
        ),
    ]
