# Generated by Django 3.1.8 on 2021-06-21 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminUI', '0064_admins_sigun_in_one'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachers',
            name='sigun_in_one',
            field=models.BooleanField(default=False, verbose_name='sigun_in_one'),
        ),
    ]
