# Generated by Django 3.1.8 on 2021-06-21 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminUI', '0066_auto_20210621_0734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admins',
            name='sign_in_one',
            field=models.BooleanField(default=True, verbose_name='sign_in_one'),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='sign_in_one',
            field=models.BooleanField(default=True, verbose_name='sign_in_one'),
        ),
    ]
