# Generated by Django 3.1.8 on 2021-06-28 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminUI', '0067_auto_20210621_0740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='contract_number',
            field=models.CharField(max_length=45, verbose_name='contract_number'),
        ),
    ]
