# Generated by Django 3.1.8 on 2021-06-30 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminUI', '0070_auto_20210628_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group_lesons',
            name='shedul_leson',
            field=models.BooleanField(default=False, null=True, verbose_name='shedul_leson'),
        ),
    ]
