# Generated by Django 3.1.8 on 2021-07-08 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminUI', '0071_auto_20210630_0813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
    ]
