# Generated by Django 3.1.8 on 2021-07-15 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminUI', '0073_studnets_language_last_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='set_expiry_time',
            field=models.DateTimeField(null=True),
        ),
    ]
