# Generated by Django 3.1.8 on 2021-07-16 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminUI', '0074_students_set_expiry_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='token_user',
            field=models.TextField(max_length=250, null=True),
        ),
    ]
