# Generated by Django 3.1.8 on 2021-07-30 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminUI', '0003_admins_logo'),
        ('adminUI', '0075_students_token_user'),
    ]

    operations = [
    ]
